---
title: "Twain Analysis"
author: ""
date: ""
output: 
  html_document:
    fig_height: 3
    fig_width: 5
  pdf_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
library(mosaic) 
library(XML)
library(readr)
library(devtools)
library(stringr)
library(RCurl)
library(syuzhet)
library(tm)

# Some customization.  You can alter or delete as desired (if you know what you are doing).
trellis.par.set(theme=theme.mosaic()) # change default color scheme for lattice
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```

```{r}
# getting texts and cleaning them
roughingitURL <- "http://www.gutenberg.org/files/3177/3177.txt"
roughingittext <- scan(roughingitURL, what = "character", sep = "\n")
innocentsURL <- "http://www.gutenberg.org/files/3176/3176-0.txt"
innocentstext <- scan(innocentsURL, what = "character", sep = "\n")
huckfinnURL <- "http://www.gutenberg.org/files/76/76-0.txt"
huckfinntext <- scan(huckfinnURL, what = "character", sep = "\n")
tomsawyerURL <- "http://www.gutenberg.org/files/74/74-0.txt"
tomsawyertext <- scan(tomsawyerURL, what = "character", sep = "\n")
connyankeeURL <- "http://www.gutenberg.org/files/86/86-0.txt"
connyankeetext <- scan(connyankeeURL, what = "character", sep = "\n")
puddURL <- "http://www.gutenberg.org/files/102/102-0.txt"
puddtext <- scan(puddURL, what = "character", sep = "\n")

# End of Project Gutenberg’s Roughing It, by Mark Twain (Samuel Clemens)
# End of the Project Gutenberg EBook of The Innocents Abroad
# End of the Project Gutenberg EBook of Adventures of Huckleberry Finn,
# End of the Project Gutenberg Ebook of Adventures of Tom Sawyer,
# End of the Project Gutenberg EBook of A Connecticut Yankee in King Arthur’s

# functions to find start and end of story
findstart <- function(text){ 
  startend <- 0
  for (i in 1:length(text)){
    if (text[i] == "CHAPTER I") {
      startend <- i
    }
  }
  for (j in 50:length(text)){
    if (text[j] == "CONCLUSION") {
      startend <- c(startend, j)
      return(startend)
    }
  }
} 

actualtext <- function(text, startend){
  realtext <- text[startend[1]:startend[2]]
  return (realtext)
}

# actual texts
roughstartend <- findstart(roughingittext)
roughingittext <- actualtext(roughingittext, roughstartend)

innocentstartend <- findstart(innocentstext)
innocentstext <- actualtext(innocentstext, innocentstartend)

huckfinnstartend <- findstart(huckfinntext)
huckfinntext <- actualtext(huckfinntext, huckfinnstartend)

tomsawyerstartend <- findstart(tomsawyertext)
tomsawyertext <- actualtext(tomsawyertext, tomsawyerstartend)
tomsawyertext <- iconv(tomsawyertext,"WINDOWS-1252","UTF-8")

connyankeestartend <- findstart(connyankeetext)
connyankeetext <- actualtext(connyankeetext, connyankeestartend)

puddstartend <- findstart(puddtext)
puddtext <- actualtext(puddtext, puddstartend)

write.table(roughingittext, "roughingit.txt", sep = "\t")
write.table(innocentstext, "innocents.txt", sep = "\t")
write.table(tomsawyertext, "tomsawyer.txt", sep = "\t")
write.table(huckfinntext, "huckfinn.txt", sep = "\t")
write.table(connyankeetext, "connyankee.txt", sep = "\t")
write.table(puddtext, "pudd.txt", sep = "\t")
```

```{r, warning = FALSE}
# sentiment analysis: Roughing It
roughsent <- get_sentiment(roughingittext, "syuzhet")
roughsenttrans <- as.numeric(get_transformed_values(roughsent, 
                                  low_pass_size = 3,
                                  scale_vals = TRUE,
                                  scale_range = FALSE))
roughsentdata <- data.frame(cbind(linenumber = seq_along(roughsenttrans), ft = roughsenttrans))

ggplot(data = roughsentdata, aes(x = linenumber, y = ft)) +
        geom_bar(stat = "identity", alpha = 0.8, color = "midnightblue", fill = "midnightblue") +
        theme_minimal() +
        ylab("Transformed Sentiment Value") +
        ggtitle(expression(paste("Sentiment in ", italic("Roughing It")))) +
        theme(axis.title.x=element_blank()) +
        theme(axis.ticks.x=element_blank()) +
        theme(axis.text.x=element_blank())
```

```{r}
tomsent <- get_sentiment(tomsawyertext, "syuzhet")
tomsenttrans <- as.numeric(get_transformed_values(tomsent, 
                                  low_pass_size = 3,
                                  scale_vals = TRUE,
                                  scale_range = FALSE))
tomsentdata <- data.frame(cbind(linenumber = seq_along(tomsenttrans), ft = tomsenttrans))

ggplot(data = tomsentdata, aes(x = linenumber, y = ft)) +
        geom_bar(stat = "identity", alpha = 0.8, color = "midnightblue", fill = "midnightblue") +
        theme_minimal() +
        ylab("Transformed Sentiment Value") +
        ggtitle(expression(paste("Sentiment in ", italic("The Adventures of Tom Sawyer")))) +
        theme(axis.title.x=element_blank()) +
        theme(axis.ticks.x=element_blank()) +
        theme(axis.text.x=element_blank()) +
ggplot2::annotate("text", size = 3, x = c(8, 18, 22, 38, 71, 85), 
                 y = c(2.3, -1.3, 1.5, .9, 1.1, -1.1), 
                 label = c("Meets Amy Lawrence", "Falls in love\n with Becky",
                           "Witness graveyard\n murder", "Escape to island",
                           "Trial of Potter and Injun Joe", "Huck saves widow")) +
        ggplot2::annotate("segment", arrow = arrow(length = unit(0.03, "npc")),
                 x = c(8, 18, 22, 38, 71, 87), xend = c(8, 18, 22, 38, 71, 87),
                 y = c(2.2, -1, 1.2, .8, 1, -1), 
                 yend = c(1.7, -.1 , 0.3, .1, .3, -.2))
```


```{r, warning = FALSE}
# sentiment across entire life
early <- c(roughingittext, innocentstext)
earlylen <- length(early)
middle <- c(huckfinntext, tomsawyertext)
midlen <- length(middle)
late <- c(connyankeetext, puddtext)

allworks <- c(early, middle, late)

allworkssent <- get_sentiment(allworks, "syuzhet")
allworkssenttrans <- as.numeric(get_transformed_values(allworkssent, 
                                  low_pass_size = 3,
                                  scale_vals = TRUE,
                                  scale_range = FALSE))
allworksdata <- data.frame(cbind(linenumber = seq_along(allworkssenttrans), ft = allworkssenttrans))

ggplot(data = allworksdata, aes(x = linenumber, y = ft)) +
        geom_bar(stat = "identity", alpha = 0.8, color = "midnightblue", fill = "midnightblue") +
        theme_minimal() +
        ylab("Transformed Sentiment Value") +
        ggtitle(expression(paste("Sentiment in Twain's works "))) +
        theme(axis.title.x=element_blank()) +
        theme(axis.ticks.x=element_blank()) +
        theme(axis.text.x=element_blank()) 
        #annotate("text", size = 3, x = c(54, 82), 
                 #y = c(1, -1),
                 #label = c("End of early works", "End of middle works")) 
   #annotate("segment", arrow = arrow(length = unit(0.03, "npc")),x = c(49,75), 
                #xend = c(49, 75),y = c(.9, -.9),yend = c(.3, -.4))
```

```{r, include=FALSE}
library(stringr)
library(plyr)
library(tm)
library(tm.plugin.mail)
library(SnowballC)
library(topicmodels)
```

```{r, warning = FALSE}
# divide up all works by chapters

# Function to divide texts up into chapters 
chapters <- function(text, numbchap) {
  chapterroman <- as.roman(1:numbchap)
  chaptercounter <- 1
  chapterlines <- 0
  for (i in 1:length(text)) {
    if (text[i] == paste("CHAPTER",chapterroman[chaptercounter], sep = " ")) {
      #paste(chapterroman[chaptercounter], ".", sep = "")
      chapterlines <- c(chapterlines, i)
      chaptercounter <- chaptercounter + 1
    }
  }
  chapterlines <- chapterlines[-1]
  for (i in 1:length(chapterlines)) {
    title <- paste("CCh", i, ".txt", sep ="")
    j <- i + 1
    write.table(text[chapterlines[i]:chapterlines[j]], title, sep = "\t")
  } 
}

# new files each containing one chapter
chapters(roughingittext, 79)
chapters(innocentstext, 60)
chapters(huckfinntext, 42)
chapters(tomsawyertext, 35)
chapters(connyankeetext, 44)
chapters(puddtext, 21)
```

```{r}
#LDA

twaincorpus <- Corpus(DirSource("/home/class17/sxu17/XuACComps/TwainTexts"))

extendedstopwords=c("a","about","above","across","after","MIME Version","forwarded","again","against","all","almost","alone","along","already","also","although","always","am","among","an","and","another","any","anybody","anyone","anything","anywhere","are","area","areas","aren't","around","as","ask","asked","asking","asks","at","away","b","back","backed","backing","backs","be","became","because","become","becomes","been","before","began","behind","being","beings","below","best","better","between","big","both","but","by","c","came","can","cannot","can't","case","cases","certain","certainly","clear","clearly","come","could","couldn't","d","did","didn't","differ","different","differently","do","does","doesn't","doing","done","don't","down","downed","downing","downs","during","e","each","early","either","end","ended","ending","ends","enough","even","evenly","ever","every","everybody","everyone","everything","everywhere","f","face","faces","fact","facts","far","felt","few","find","finds","first","for","four","from","full","fully","further","furthered","furthering","furthers","g","gave","general","generally","get","gets","give","given","gives","go","going","good","goods","got","great","greater","greatest","group","grouped","grouping","groups","h","had","hadn't","has","hasn't","have","haven't","having","he","he'd","he'll","her","here","here's","hers","herself","he's","high","higher","highest","him","himself","his","how","however","how's","i","i'd","if","i'll","i'm","important","in","interest","interested","interesting","interests","into","is","isn't","it","its","it's","itself","i've","j","just","k","keep","keeps","kind","knew","know","known","knows","l","large","largely","last","later","latest","least","less","let","lets","let's","like","likely","long","longer","longest","m","made","make","making","man","many","may","me","member","members","men","might","more","most","mostly","mr","mrs","much","must","mustn't","my","myself","n","necessary","need","needed","needing","needs","never","new","newer","newest","next","no","nobody","non","noone","nor","not","nothing","now","nowhere","number","numbers","o","of","off","often","old","older","oldest","on","once","one","only","open","opened","opening","opens","or","order","ordered","ordering","orders","other","others","ought","our","ours","ourselves","out","over","own","p","part","parted","parting","parts","per","perhaps","place","places","point","pointed","pointing","points","possible","present","presented","presenting","presents","problem","problems","put","puts","q","quite","r","rather","really","right","room","rooms","s","said","same","saw","say","says","second","seconds","see","seem","seemed","seeming","seems","sees","several","shall","shan't","she","she'd","she'll","she's","should","shouldn't","show","showed","showing","shows","side","sides","since","small","smaller","smallest","so","some","somebody","someone","something","somewhere","state","states","still","such","sure","t","take","taken","than","that","that's","the","their","theirs","them","themselves","then","there","therefore","there's","these","they","they'd","they'll","they're","they've","thing","things","think","thinks","this","those","though","thought","thoughts","three","through","thus","to","today","together","too","took","toward","turn","turned","turning","turns","two","u","under","until","up","upon","us","use","used","uses","v","very","w","want","wanted","wanting","wants","was","wasn't","way","ways","we","we'd","well","we'll","wells","went","were","we're","weren't","we've","what","what's","when","when's","where","where's","whether","which","while","who","whole","whom","who's","whose","why","why's","will","with","within","without","won't","work","worked","working","works","would","wouldn't","x","y","year","years","yes","yet","you","you'd","you'll","young","younger","youngest","your","you're","yours","yourself","yourselves","you've","z")
dtm.control = list(
  tolower = T,
  removePunctuation = T,
  removeNumbers = T,
  stopwords = c(stopwords("english"),extendedstopwords),
  stemming = T,
  wordLengths = c(3,Inf),
  weighting = weightTf)

dtm = DocumentTermMatrix(twaincorpus, control=dtm.control)
dtm = removeSparseTerms(dtm,0.999)
dtm = dtm[rowSums(as.matrix(dtm))>0,]

k = 4
lda.model = LDA(dtm, k)
terms(lda.model,20)
```


